### ISSUE TITLE
Rethinkdbdash

### ISSUE THREAD

**Issue by debdattabasu** [types/npm-rethinkdb#8] opened 2017-03-05 14:27 UTC
Hi. 
In the older repo there was a definition for rethinkdbdash. Why was it dropped, and are there plans to continue? 

I am currently using the older version, and it seems to work fine. 

Regards

**Comment by niieani** [comment] 2017-03-05 19:51
Hi.

I've had trouble porting the rethinkdbdash to enhance these typings (https://github.com/types/npm-rethinkdb/issues/4). It's probably resolved by now, but I'd need to try again. Feel free to create a repo and we'll migrate it over here, under @types.

**Comment by marshall007** [comment] 2017-04-18 23:49
@niieani I was trying to take a stab at this, but I'm stuck. I started by extracting the ReQL instance methods into an interface `ReqlInstance` and then exporting everything that was formerly the `rethinkdb` namespace as `ReQL`. That way we could augment and re-export the `ReQL` namespace for both `rethinkdb` and `rethinkdbdash`.

https://gist.github.com/marshall007/ee9bfde77871732744dfb1de2760811b#file-rethinkdbdash-d-ts-L4-L11

However, using this simple test snippet, it doesn't seem like any of my augmentations to the `ReQL` namespace are actually being picked up:

```ts
r.db('test').table('test')
.filter({ foo: 'bar' })
.toStream()
```

Any thoughts?

**Comment by blakeembrey** [comment] 2017-04-18 23:56
@marshall007 The lines you linked to aren't a module augmentation, just a regular namespace/interface. To make it work, you need to import the module and then `declare module "same-name-as-import-here-to-augment"`. There's some more info in https://www.typescriptlang.org/docs/handbook/declaration-merging.html. Someone seems to have gotten it working with https://github.com/types/npm-rethinkdb/issues/4#issuecomment-260134132, so it might be worth checking out.

**Comment by marshall007** [comment] 2017-04-19 00:00
@blakeembrey thanks! I was basing my implementation on [`method-override`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/method-override/index.d.ts) from the DefinitelyTyped repo (notice how he extends the `Express.Request` interface). Can you elaborate on the differences between the two? They seem to be using `declare namespace` in that example and it works.

**[edit]:** you're right though. If I change mine to `declare module 'reql' { ... }` it does seem to work!

**Comment by blakeembrey** [comment] 2017-04-19 00:16
I think the differences are best described in the page I linked in the previous comment. The example you linked me to is just using namespace + function merging (you can merge a few different types together, there's a chart in the link above, which enables you to emulate traditional JavaScript properly).

**Comment by marshall007** [comment] 2017-04-19 01:14
@blakeembrey ok, I think I understand correctly. Is the difference that when you merge namespaces, the merged namespace value is only defined at the declaration site whereas _augmentation_ implies that you are actually modifying the module declaration?

So in the `method-override` example, consumers of that package will only see the `originalMethod` property of the `Request` interface in the context of the exported function? In other words, they _will not_ see `originalMethod` defined on the `Request` interface of the `express` module itself?

**Comment by blakeembrey** [comment] 2017-04-19 02:36
Oh, sorry - now I understand the question better 😄  In reality, both features exist (you're using that feature to augment the module). The difference is yes, the change occurs in the context you're writing the interface. So if you're writing it in a module, all you're doing is writing a new interface with the same name as another interface in another module. To work around this, you use module augmentation to specifically augment a module (or you rely on all the interfaces being global). 

So yes, in your example, no one will see the augmentation on Express - there isn't one. The only way to access it is from `e`. Honestly, I have no idea what the `namespace Express` is doing above it - it looks like a bug or bad refactor, but it shouldn't do anything since there's no augmentation.

Edit: Confirmed. It used to be written in a "global" style where those namespaces would have previously merged. The existence of `namespace Express` there now is a bug.

**Comment by marshall007** [comment] 2017-04-19 02:45
@blakeembrey my understanding was that it would merge the namespace defined in [`express-serve-static-core`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/express-serve-static-core/index.d.ts#L13), which is then re-exported as `express.Request` [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/express/index.d.ts#L66).

Based on what you're saying though, since the module is not actually being augmented, `express.Request` used later in the `method-override` shouldn't see the additional `originalMethod` member?

**Comment by blakeembrey** [comment] 2017-04-19 02:59
It can't possibly, no. It's broken. If you look at the blame and previous commits, you can see it was broken in a mega-PR changing from global types to module types.

**Comment by blakeembrey** [comment] 2017-04-19 03:01
I'd be curious if this does work somehow, but reading through the code it definitely _shouldn't_ because one is "global" while the other is purely local to the module and just considered dead code.

**Comment by blakeembrey** [comment] 2017-04-19 03:04
@marshall007 I believe that even that comment is wrong. If you look at the blame once more, there's just a bunch of misdirection and a few broken changes. See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12425/files#diff-f2a8fc6d3e66a77a1c4e4663e1900689L8, which just copies and pastes the same code into `declare global`. I believe all this code used to work before the UMD refactor (giant PR moving to external modules: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/c17b1b78b886e84afe27e1b65fe5bf901da5bbe7) so hasn't worked in over 11 months or so now, or since NPM `@types` were released.

**Comment by marshall007** [comment] 2017-04-19 18:50
@blakeembrey thanks, that helps a lot. It's a shame I just happened to pick a broken example to work from, haha.

I think I'm really close now, `rethinkdbdash` is working great. The last issue I'm having is re-exporting `core.ReqlInstance` as the `rethinkdb` namespace (link below). I can't even really decide if exporting an external interface like that is supported.

https://gist.github.com/marshall007/ee9bfde77871732744dfb1de2760811b#file-rethinkdb-d-ts-L3-L6

**Comment by blakeembrey** [comment] 2017-04-19 20:25
What's the issue or error you're running into? `export as namespace` means "this module is actually a global if no one imports it". It's a way of TypeScript enabling UMD in definitions. Not sure if that's what you're after. The other thing is, `export default` and `export =` mean different things. `export =` is like `module.exports =` in CommonJS, while `export default` is just `exports.default` in CommonJS. One or the other won't work at runtime if the library is written the opposite way in JS. Not sure if either of those were your actual question/issue, so feel free to rephrase if I misinterpreted 😄

**Comment by marshall007** [comment] 2017-04-19 21:02
@blakeembrey ah, ok. I had started with the `export =` syntax and (incorrectly) thought it wasn't working. So given the following `rethinkdb.d.ts` definition:

```ts
import * as core from 'rethinkdb-core';

declare const rethinkdb: core.ReqlInstance;
export = rethinkdb;
```

```ts
import * as rethinkdb from 'rethinkdb';

rethinkdb.table('foo'); // works

const r: rethinkdb = require('./db'); // TS Error: Cannot find name 'rethinkdb'.
```

Where `./db.js` is simply doing `module.exports = require('rethinkdb')`. Is there a reason I cannot use `rethinkdb` as a type annotation in this case?

**Comment by marshall007** [comment] 2017-04-19 21:13
I guess I should just be doing something like this instead:

```ts
import * as core from 'rethinkdb-core';

declare const rethinkdb: core.ReqlInstance;

declare namespace rethinkdb {
  export interface ReqlInstance extends core.ReqlInstance { }
}

export = rethinkdb;
```

```ts
import * as rethinkdb from 'rethinkdb';
const r: rethinkdb.ReqlInstance = require('./db');
```

**Comment by blakeembrey** [comment] 2017-04-19 22:09
> Is there a reason I cannot use rethinkdb as a type annotation in this case?

Yep, it's a value. Use `typeof rethinkdb` to get the type.

**Comment by marshall007** [comment] 2017-04-19 22:55
@blakeembrey I've submitted a PR in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16006. Would appreciate if you could review.

**Comment by blakeembrey** [comment] 2017-04-20 00:32
@marshall007 I would have asked either of us before using the code. Especially since you've violated the license and used your name in place of ours. I've personally spent cumulative of a weeks worth complete work days on the definition and I'm sure @niieani has spent more time than that getting to the initial version in his repo.

That said, please don't publish a `rethinkdb-core` module. There's no module called `rethinkdb-core` published to NPM, and it's just confusing. This would be doable without it. If you're following the Express example again, it's a really bad example to follow and I wouldn't recommend following it further. In fact, @types has a better implemented version of Express.js at https://github.com/types/npm-express. 

Another thing, and this is a general DefinitelyTyped/NPM issue that's unsolved, if this is published it _will_ break anyone using the existing definition.

**Comment by marshall007** [comment] 2017-04-20 01:36
@blakeembrey really sorry, I didn't mean to step on anyone's toes. My impression was that this issue and https://github.com/DefinitelyTyped/DefinitelyTyped/issues/4551 (and an overarching theme of TS 2.x) was aimed at migrating everything to `@types/<package>`. Frankly, it's just really confusing trying to navigate the current state of tsd management so I apologize. I'm just trying to make sure our team can manage all our definitions via npm only.

> Especially since you've violated the license and used your name in place of ours.

DefinitelyTypes is licensed MIT as well, so I assumed all contributions inherited the same license. I tried to be very clear about attributions both in the PR description and the [definition files](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16006/files#diff-27a611e300d9241d62722e8cfd1c305dR3). I will certainly add you as well.

> That said, please don't publish a `rethinkdb-core` module. [...] This would be doable without it.

I'm all ears in terms of better approaches to all of this. I was just trying to reference packages with similar requirements that I had in my project as examples. I was also hoping to make this as extensible as possible so that we might support other drivers in the future, like `thinky`. Publishing `rethinkdb-core` seemed to be the only way to accomplish that, but like I said I'm totally open to suggestions.

**Comment by blakeembrey** [comment] 2017-04-20 05:14
So if you read the MIT license, it says that the copyright license must be included. Aside from that, you can request the Microsoft team enable this at https://github.com/Microsoft/types-publisher/issues/4 - I've been waiting a year to be able to put our repos on DefinitelyTyped. In the current state of you just copying and pasting it, will you be responsible for copying any contributions on DefinitelyTyped back here? Or will you update it with contributions from here in the future? If every user just takes code myself and others have spent years writing and puts it on DefinitelyTyped without attribution, I'm sure you can understand how upsetting that might be (this is just one definition of hundreds I've written, and although I had a good template to work from with the previous definitions written it still took weeks of man hours for myself to complete).

On the core type, it's not needed at all. Just delete it, nothing changes for extensibility. He fact that the definition you copied from uses it is a stupid issue and it shouldn't exist either.

**Comment by blakeembrey** [comment] 2017-04-20 05:22
Also, if your goal is just to manage it with NPM, you can install from Git - `npm install types/npm-rethinkdb` would work.

**Comment by marshall007** [comment] 2017-06-07 23:07
@blakeembrey I'd like to take another stab at this. Can you elaborate on how we might workaround not having shared `rethinkdb-core` definitions that would be referenced from the native driver and `rethinkdbdash`?

One issue I was running into is that the two drivers are just different enough to where simply extending the definitions from this repo results in confusing and misleading overloads. For example, `rethinkdbdash` returns `Array<T>` by default unless you call `.run({ cursor: true })`.

**Comment by marshall007** [comment] 2017-06-14 23:55
Just waiting on https://github.com/typings/registry/pull/993.

**Closed as completed by marshall007** 2017-06-14 23:55 UTC
